### ISSUE TITLE
Highlight escaped backticks in a interpolation string correctly

### ISSUE THREAD

**Issue by ryyppy** [ryyppy/vim-rescript#54]
Given following code:

```
let a = "abc"


let str = "aaa\"bbb"

Js.log(` \` ccc ${a} ddd  `)


Js.log(`a = ${a}`)

Js.log(``)

let b = 34

let parser = %raw(`
  
adsfadsfzz
`)

```

Will break the syntax highlighting:

![image](https://user-images.githubusercontent.com/1121889/150497162-fe261ce5-5729-46d3-bf3b-9bc08e1ff3c4.png)

We [fixed this in rescript-vscode](https://github.com/rescript-lang/rescript-vscode/commit/a4e40e794e67c2b6c5ff2874c75fbc327e660dbb) with a negative lookbehind that also matches escaped backticks, but we couldn't get it to work for vim yet.

@amiralies any idea how to solve this? Would be even greater to highlight the escaped backtick in a different color, like in common strings.

**Comment by amiralies** [comment]
Will take a look tomorrow. It should be trivial
