### ISSUE TITLE
Support Linux ARM

### ISSUE THREAD

**Issue by ellbur** [ryyppy/vim-rescript#60]
Everything runs fine on Linux ARM with the exception that the server does not use the correct analysis binary.

A [change is needed to the server](https://github.com/ellbur/rescript-vscode/commit/737a6a47df317eeca7f5a815507d6936b6415baa) to select a different binary depending on the architecture.

Then the [updated server](https://github.com/ellbur/vim-rescript/commit/5e6a1a90cf1ea7bee35a4e4f780ffdc63a406c4c) and [appropriate binary](https://github.com/ellbur/vim-rescript/commit/222b53d19643be03fb6dbf2b5030509e105f71ec) must be included here.

Then everything works fine!

**Comment by ryyppy** [comment]
Can you open a separate issue on rescript-vscode and link it here? Makes it easier to coordinate the fix.

**Comment by ellbur** [comment]
Hi @ryyppy 

Here's the issue on rescript-vscode: https://github.com/rescript-lang/rescript-vscode/issues/426 Some kinks are being worked out on it.

**Comment by ryyppy** [comment]
Thanks! will close this thread in favour of the linked issue if you don't mind.
