### ISSUE TITLE
Add support for commenting 

### ISSUE THREAD

**Issue by dmtrKovalenko** [ryyppy/vim-rescript#75]
Neovim v10 has a built-in commenting support based on the treesitter. But rescript files can not be commented, and failing with the following error: 

```
Option 'commentstring' is empty.
```

**Comment by aspeddro** [comment]
I think this should be done in https://github.com/rescript-lang/vim-rescript

Or create a file at `~/.config/nvim/after/ftplugin/rescript.lua`

```lua
vim.opt_local.commentstring = '// %s'
```
